language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t damiengulliver/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true damiengulliver/react-test npm test


after_success:
  - docker build -t damiengulliver/multi-client ./client
  - docker build -t damiengulliver/multi-nginx ./nginx
  - docker build -t damiengulliver/multi-server ./server
  - docker build -t damiengulliver/multi-worker ./worker