language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t damiengulliver/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true damiengulliver/react-test npm test

after_success:
  - docker build -t damiengulliver/multi-client ./client
  - docker build -t damiengulliver/multi-nginx ./nginx
  - docker build -t damiengulliver/multi-server ./server
  - docker build -t damiengulliver/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push damiengulliver/multi-client
  - docker push damiengulliver/multi-nginx
  - docker push damiengulliver/multi-server
  - docker push damiengulliver/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'ap-southeast-2'
  app: 'multi-container-docker'
  env: 'Multicontainerdocker-env'
  bucket_name: 'elasticbeanstalk-ap-southeast-2-434016983317'
  bucket_path: 'docker-multi'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY